name: ten_minute_mail
description: A client library for 10MinuteMail and receiving temporary mails.
version: 0.1.2
homepage: https://github.com/Lukas-Heiligenbrunner/ten-minute-mail

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
