name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: flutter format . --output none --set-exit-if-changed

      - name: Run Dart analyzer
        run: flutter analyze ./lib ./example

      - name: Run tests
        run: flutter test -r expanded test/main_test.dart
